config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    devise_scope :user do
      root to: "users#show", :as => "profile"
    end
  end
  unauthenticated do
    devise_scope :user do
      root to: "landing_pages#home", :as => "landing"
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :student_preferences
  resources :supervisor_preferences

  match '/welcome',   to: 'welcome#welcome', via: :get
  match '/welcome2',  to: 'welcome#welcome2', via: :get
  match '/welcome3',  to: 'welcome#welcome3', via: :get

end

app/views/layouts/_footer.html.erb
<footer id="contact" class="footer">

      <div class="container">    
        <div class="row">
          <div class="col-lg-12">
            <div class="col-sm-3 col-md-3">
              <div class="footer-logo">
                <h2>Therapitize</h2>
                <p>718 Washington Ave N #308 Minneapolis, MN 55401 <br> (507) 400-2678</p>
                <br>
                <p class="muted">© 2014 therapitize.me</p>
                <!--<a href="#">Terms of Service</a>    
                <a href="#">Privacy</a>-->
              </div>
            </div>
           <div class="col-sm-3 col-md-3">
              <!-- <h3>Product</h3>
              <ul class="list-unstyled">
                <li><a href="#">Product for iOS</a></li>
                <li><a href="#">Product for Android</a></li>
                <li><a href="#">Product for Windows</a></li>           
              </ul>-->
            </div>
            <div class="col-sm-3 col-md-3">
              <!--<h3>Company</h3>
              <ul class="list-unstyled">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Our Team</a></li>
                <li><a href="#">Jobs&emsp;<span class="label label-info">We're hiring!</span></a></li>           
              </ul>-->
            </div>
            <div class="col-sm-3 col-md-3">
              <h3>Company</h3>
              <ul class="list-unstyled">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Our Team</a></li>        
              </ul>
            </div>  
          </div>
        </div>
      </div>

    </footer>

app/views/layouts/_header.html.erb
<%= render 'layouts/messages' %>
<nav class="navbar" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "THERAPITIZE", profile_path, class: "navbar-brand" %>
    </div>

    <% if signed_in? %>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Settings", edit_user_path(@user) %></li>
          <li><a href="#about">About</a></li>
          <li><a href="#featured1">Contact</a></li>
          <li><%= link_to "SIGN OUT", destroy_user_session_path, class: "main_nav_box header-link ", :method => :delete %></li>
        </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/_landing_header.html.erb
<div class="navbar-wrapper cbp-af-header">
<%= render 'layouts/messages' %>
  <div class="container">

    <!-- Fixed navbar -->
    <div class="navbar cbp-af-inner" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h1><a class="navbar-brand scroll" href="#intro">THERAPITIZE</a></h1>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav pull-right">
            <li><a href="#about">About</a></li>
            <li><a href="#featured1">Contact</a></li>
            <li><a class="login" href="#">LOG IN</a></li>
          </ul>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <center><%= content_tag :div, msg, :id => "flash_#{name}" %></center>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Therapitize" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Therapitize" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrap">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= javascript_include_tag 'application'%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Therapitize" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Therapitize" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'landing', media: 'all' %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>

    <%= csrf_meta_tags %>

  </head>
  <body>
    <main role="main">
       <%= render 'layouts/landing_header' %>
       <%= yield %>
       <%= render 'layouts/footer' %>
    </main>
    <%= javascript_include_tag 'application'%>
    <%= javascript_include_tag 'landing' %>
    <script>

      $(document).ready(function(){
        isotope();
        studentSignupOverlay();
        superSignupOverlay();
        loginOverlay();
      });

    </script>
  </body>
</html>